services:
  server:
    image: weather-station
    build:
      context: ./
      dockerfile: src/docker/Dockerfile
      target: base
    restart: always
    volumes:
      - ./src/server:/var/www/html:ro
      - ./src/database:/weather-station/database
    environment:
      - METEO_DB_HOST=mysql
      - METEO_DB_NAME=estacion_perseverance
      - METEO_DB_USERNAME=root
      - METEO_DB_PASSWORD=root
    ports:
      - 127.0.0.1:8000:80

  mysql:
    image: mysql:5.7-debian
    platform: linux/amd64
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=estacion_perseverance
    ports:
      - 127.0.0.1:3306:3306

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    environment:
      - PMA_HOST=mysql
    ports:
      - 127.0.0.1:8001:80

  grafana:
    image: grafana/grafana-oss
    restart: always
    ports:
      - 127.0.0.1:8002:80
    environment:
      - GF_SERVER_HTTP_PORT=80
