services:
  weather-station:
    image: ghcr.io/pamplonetario/weather-station:${WEATHER_STATION_VERSION:-local}
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./src/server:/var/www/html:ro
      - ./src/schema:/weather-station/schema
    environment:
      - METEO_DB_HOST=weather-station-mysql
      - METEO_DB_NAME=estacion_perseverance
      - METEO_DB_USERNAME=root
      - METEO_DB_PASSWORD=root
    ports:
      - 127.0.0.1:8000:80

  weather-station-mysql:
    image: mysql:5.7-debian
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=estacion_perseverance
    volumes:
      - ./src/database:/weather-station/database:ro
    ports:
      - 127.0.0.1:3306:3306

  weather-station-phpmyadmin:
    image: phpmyadmin:5.2
    environment:
      - PMA_HOST=weather-station-mysql
    ports:
      - 127.0.0.1:8001:80

  weather-station-grafana:
    image: grafana/grafana-oss:10.0.3
    ports:
      - 127.0.0.1:8002:80
    environment:
      - GF_SERVER_HTTP_PORT=80
