services:
  server:
    build:
      context: ./
      dockerfile: src/docker/Dockerfile
    restart: always
    volumes:
      - ./src/server:/var/www/html:ro
    environment:
      - METEO_DB_HOST=mysql
      - METEO_DB_NAME=estacion_perseverance
      - METEO_DB_USERNAME=root
      - METEO_DB_PASSWORD=root

  mysql:
    image: mysql:5.7-debian
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    environment:
      - PMA_HOST=mysql

  grafana:
    image: grafana/grafana-oss
    restart: always
