services:
  weather-station-server:
    build:
      target: development
    volumes:
      - ./src/server:/var/www/html:ro
      - ./src/schema:/weather-station/schema
    environment:
      - METEO_DB_HOST=weather-station-mysql
      - METEO_DB_NAME=estacion_perseverance
      - METEO_DB_USERNAME=root
      - METEO_DB_PASSWORD=root
    ports:
      - 127.0.0.1:8000:80

  weather-station-mysql:
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=estacion_perseverance
    volumes:
      - ./src/database:/weather-station/database:ro
    ports:
      - 127.0.0.1:3306:3306

  weather-station-phpmyadmin:
    environment:
      - PMA_HOST=weather-station-mysql
    ports:
      - 127.0.0.1:8001:80

  weather-station-grafana:
    ports:
      - 127.0.0.1:8002:80
    environment:
      - GF_SERVER_HTTP_PORT=80
