services:
  weather-station-server:
    build:
      context: ./
      dockerfile: src/docker/Dockerfile

  weather-station-mysql:
    image: mysql:5.7-debian

  weather-station-phpmyadmin:
    image: phpmyadmin:5.2

  weather-station-grafana:
    image: grafana/grafana-oss:10.0.3
